# src/eveg/AppBundle/Resources/config/routing.yml

# application routes
eveg_app_homepageEmpty:
    path: /
    defaults: { _controller: evegAppBundle:Default:index }

eveg_app_homepage:
    path:     /accueil
    defaults: { _controller: evegAppBundle:Default:index }

eveg_app_howto:
    path: /utiliser
    defaults: { _controller: evegAppBundle:Default:howto }

eveg_app_contact:
    path: /contact
    defaults: { _controller: evegAppBundle:Default:contact }

# Admin routes
eveg_admin :
  resource: "routing_admin.yml"
  prefix:  /admin