# src/eveg/AppBundle/Resources/config/routing_admin.yml

# Admin routes
eveg_admin_dashboard:
    path: /
    defaults: { _controller: evegAppBundle:Admin:dashboard }

eveg_admin_test:
    path: /test
    defaults: { _controller: evegAppBundle:Admin:test }