parameters:
#    eveg_app.example.class: eveg\AppBundle\Example

services:
    # catCode services
    # Those 2 services are separated because only the second one (catCodeRepo) uses the repository.
    # >> We can't set up a function that doesn't use the repository in the catCodeRepo because doctrine factory service
    #     only expects find, findBy, get... functions.
    # All services provided by catCodeRepo are 'duplicated' in the catCode service to make things easier.
    eveg_app.catCode:
        class:             eveg\AppBundle\Utils\CatCode\evegCatCode
        arguments:         ['@eveg_app.catCodeRepo', '@eveg_app.repFilters']

    eveg_app.catCodeRepo:
        class:             eveg\AppBundle\Utils\CatCode\evegCatCodeRepo
        factory_service:   doctrine.orm.default_entity_manager
        factory_method:    getRepository
        arguments:         ['evegAppBundle:SyntaxonCore']

    eveg.twig.eveg_extension:
        class:             eveg\AppBundle\Twig\evegExtension
        tags:
            - { name: twig.extension }

    eveg_app.repFilters:
        class:              eveg\AppBundle\Utils\RepartitionFilters\evegRepFilters

    eveg_app.form.type.upload:
        class:              eveg\AppBundle\Form\Type\SyntaxonFileType
        arguments:          ['@security.authorization_checker', '@eveg_app.possible_diagnosis', '@request_stack']
        tags:
            - {name: form.type }

    eveg_app.form.type.addLink:
        class:              eveg\AppBundle\Form\Type\SyntaxonHttpLinkType
        arguments:          ['@security.authorization_checker']
        tags:
            - {name: form.type }

    eveg_app.form.type.photo:
        class:              eveg\AppBundle\Form\Type\SyntaxonPhotoType
        arguments:          ['@security.authorization_checker']
        tags:
            - {name: form.type }

    score_repository:
        class:              Doctrine\ORM\EntityRepository
        factory_service:    doctrine.orm.default_entity_manager
        factory_method:     getRepository
        arguments:
            - eveg\AppBundle\Entity\SyntaxonCore

    eveg_app.get_syntaxon_according_user:
        class:              eveg\AppBundle\Utils\Repository\getSyntaxonAccordingUserRights
        arguments:          ['@score_repository', '@security.authorization_checker', '@security.token_storage']

    eveg_app.get_synonyms_according_user:
        class:              eveg\AppBundle\Utils\Repository\getSynonymsAccordingUserRights
        arguments:          ['@score_repository', '@security.authorization_checker', '@security.token_storage']

    eveg_app.possible_diagnosis:
        class:             eveg\AppBundle\Utils\Repository\possibleDiagnosis
        arguments:         ['@score_repository']

    # scRepo service (used within catCode utility class)
    # Useless !?
    #eveg_app.scRepo:
    #    class: eveg\AppBundle\Entity\SyntaxonCoreRepository
    #    factory_service: doctrine.orm.default_entity_manager
    #    factory_method: getRepository
    #    arguments: ['evegAppBundle:SyntaxonCore']

