imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
#    - { resource: "@evegAppBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - "::forms.html.twig"
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["evegAppBundle"]
    #java: /usr/bin/java
    ruby: %ruby%
    filters:
        cssrewrite: ~
        sass:
            bin: %sass%
        compass:
            bin: %compass%
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Stof doctrine extension configuration
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true

#FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: eveg\UserBundle\Entity\User

    service:
        mailer: fos_user.mailer.twig_swift

    registration:
        confirmation:
            from_email:
                address: subscribe.eveg@gmail.com
                sender_name: eveg.fr
            enabled: true
        form:
            type: app_user_registration

    resetting:
        email:
            from_email: 
                address: unsubscribe.eveg@gmail.com
                sender_name: eveg.fr

    from_email:
        address: eveg@eveg.fr
        sender_name: eveg.fr

# FOS Rest configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

# FOS RoutingJs configuration
fos_js_routing:
    routes_to_expose:
        - "^api_.*"
        - "eveg_show_one"
        - "eveg_admin_catCode"

# BeSimpleI18nRoutingBundle
be_simple_i18n_routing: ~

# KNPMenuBundle
knp_menu:
    twig:
        template: evegAppBundle:Menu:knp_menu.html.twig

# VichUploader
vich_uploader:
    db_driver: orm

    mappings:
        syntaxon_photo:
            uri_prefix: /uploads/images/syntaxons
            upload_destination: %kernel.root_dir%/../web/uploads/images/syntaxons
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
            
        syntaxon_file:
            uri_prefix: /uploads/files/syntaxons
            upload_destination: %kernel.root_dir%/../web/uploads/files/syntaxons
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

# LiipImagineBundle
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        thumb:
            quality: 90
            filters:
                auto_rotate: ~
                thumbnail: { size: [300, 300], mode: inset }
        resized:
            filters:
                auto_rotate: ~
                relative_resize: { widen: 1000 }

# EasyAdminBundle
easy_admin:
    site_name: 'eVeg Admin'
    entities:
        Utilisateur:
            class: eveg\UserBundle\Entity\User
            list:
                fields: ['username', 'email', 'roles', 'lastLogin', 'enabled', 'locked']
            edit:
                fields: ['username', 'email', 'roles', 'enabled', 'locked']
            new:
                fields: ['username', 'email', 'roles', 'enabled', 'locked']
        Syntaxon:
            class: eveg\AppBundle\Entity\SyntaxonCore
            list:
                fields: ['id', 'catminatCode', 'level', 'syntaxonName', 'syntaxonAuthor']
            edit:
                fields: ['id', 'catminatCode', 'level', 'syntaxonName', 'syntaxonAuthor', 'repartitionDepFr']

# IvoryCkEditor
ivory_ck_editor:
    default_config: eveg_config
    configs:
        eveg_config:
            toolbar: [ ["Source", "-", "Save"], "/", ["Anchor"], "/", ["Maximize"] ]
            uiColor: "#000000"

