eveg_user:
    resource: "@evegUserBundle/Resources/config/routing.yml"
    prefix:   /

eveg_app:
    resource: "@evegAppBundle/Resources/config/routing/routing.yml"
    prefix:   /

# -------------
# FOSRestBundle
# -------------
rest:
    type: rest
    resource: "@evegAppBundle/Resources/config/routing/routing_rest.yml"
    prefix: /api

# -------------
# FOSUserBundle
# -------------
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# -------------
# FOSJsRouting
# -------------
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"