# src/eveg/AppBundle/Resources/config/routing/routing.yml

# application routes

eveg_app:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: eveg_app_homepage

eveg_app_homepage:
    locales:  { fr: "/accueil", en: "/en/homepage" }
    defaults: { _controller: evegAppBundle:Default:index }

eveg_app_activity:
    locales:  { fr: "/activités", en: "/en/activities" }
    defaults: { _controller: evegAppBundle:Default:activity }

eveg_app_participate:
    locales:  { fr: "/comment-participer", en: "/en/how-to-participate" }
    defaults: { _controller: evegAppBundle:Default:participate }

eveg_app_howto:
    locales:  { fr: "/utiliser", en: "/en/howto" }
    defaults: { _controller: evegAppBundle:Default:howto }

eveg_app_contact:
    locales:  { fr: "/contact", en: "/en/contact" }
    defaults: { _controller: evegAppBundle:Default:contact }

# We use this trick because BeSimpleI18nRoutingBundle seems to be incompatible with FOSJsRoutingBundle (I think it doesn't recognize the "locales" parameter)
eveg_show_one_redirect:
    path: /app/redirect/{id}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: eveg_show_one

eveg_show_one:
    locales:  { fr: "/app/{id}", en: "/en/app/{id}" }
    defaults: { _controller: evegAppBundle:Default:showOne }
    requirements:
        id: \d+

eveg_show_photos:
    locales:  { fr: "/app/{id}/photos", en: "/en/app/{id}/photos" }
    defaults: { _controller: evegAppBundle:SyntaxonPhoto:showPhotos }
    requirements:
        id: \d+

eveg_add_photo:
    locales:  { fr: "/app/{id}/ajouter-une-photo", en: "/en/app/{id}/add-a-picture" }
    defaults: { _controller: evegAppBundle:SyntaxonPhoto:addPhoto }
    requirements:
        id: \d+
        #_method: POST GET

eveg_edit_photo:
    locales: { fr:"/app/{id}/photo/{idPhoto}/modifier", en:"/en/app/{id}/photo/{idPhoto}/edit" }
    defaults: { _controller:evegAppBundle:SyntaxonPhoto:edit }
    requirements:
        id: \d+
        idPhoto: \d+

eveg_add_file:
    locales: { fr: "/app/{id}/ajouter-un-fichier", en: "/en/app/{id}/add-a-file" }
    defaults: { _controller: evegAppBundle:SyntaxonFile:addFile }
    requirements:
        id: \d+

eveg_edit_file:
    locales: { fr: "/app/{id}/fichier/{idFile}/modifier", en: "/en/app/{id}/file/{idFile}/edit" }
    defaults: { _controller: evegAppBundle:SyntaxonFile:editFile }
    requirements:
        id: \d+
        idFile: \d+

eveg_download_file:
    locales: { fr: "/app/{id}/fichier/{idFile}/telecharger", en: "/en/app/{id}/file/{idFile}/download" }
    defaults: { _controller: evegAppBundle:SyntaxonFile:downloadFile }
    requirements:
        id: \d+
        idFile: \d+

eveg_add_http_link:
    locales: { fr: "/app/{id}/ajouter-un-lien", en: "/en/app/{id}/add-a-link" }
    defaults: { _controller: evegAppBundle:SyntaxonHttpLink:addHttpLink }
    requirements:
        id: \d+

eveg_edit_http_link:
    locales: { fr: "/app/{id}/lien/{idHttpLink}/modifier", en: "/en/app/{id}/link/{idHttpLink}/edit" }
    defaults: { _controller: evegAppBundle:SyntaxonHttpLink:editHttpLink }
    requirements:
        id: \d+
        idHttpLink: \d+

eveg_get_http_link:
    locales: { fr: "/app/{id}/lien/{idHttpLink}", en: "/en/app/{id}/link/{idHttpLink}" }
    defaults: { _controller: evegAppBundle:SyntaxonHttpLink:getHttpLink }
    requirements:
        id: \d+
        idHttpLink: \d+

eveg_language:
    path: /language/{lang}
    defaults: { _controller: evegAppBundle:Default:setLanguage }
    requirements:
        lang: fr|en

eveg_repartition_filter:
    path: /app/repartition-filter
    defaults: { _controller : evegAppBundle:RepartitionFilter:repartitionFilter }
    requirements:
        _method: POST

eveg_download_pdf:
    locales: { fr: "/app/{id}/telecharger", en: "/en/app/{id}/download" }
    defaults: { _controller : evegAppBundle:Default:downloadPdf }

eveg_show_simple_view:
    locales: { fr: "/app/{id}/version-imprimable", en: "/en/app/{id}/printable-view" }
    defaults: { _controller : evegAppBundle:Default:simpleView }

eveg_save_repartition_map:
    path: /app/repartition/save/{mapType}
    defaults: { _controller: evegAppBundle:RepartitionImageCache:saveRepartitionMap }
    requirements:
        _method: POST

eveg_image_cache_map_exists:
    path: /app/repartition/image/exists
    defaults: { _controller: evegAppBundle:RepartitionImageCache:imageExists }
    requirements:
        _method: POST

# Feedbacks
eveg_feedback:
    path: /feedback
    defaults: { _controller: evegAppBundle:Feedback:feedback }
    requirements:
        _method: POST

# Compare
eveg_compare_nb_items:
    path: /app/compare/nb-items
    defaults: { _controller: evegAppBundle:Compare:getNbItems }

eveg_compare_get_items:
    path: /app/compare/get-items
    defaults: { _controller: evegAppBundle:Compare:getItems }

eveg_compare_add_item:
    path: /app/compare/add
    defaults: { _controller: evegAppBundle:Compare:addItem }

eveg_compare_remove_item:
    path: /app/compare/remove
    defaults: { _controller: evegAppBundle:Compare:removeItem }

eveg_compare_empty:
    path: /app/compare/empty
    defaults: { _controller: evegAppBundle:Compare:empty }

eveg_compare_get_idreferer:
    path: /app/compare/get-id-referer
    defaults: { _controller: evegAppBundle:Compare:getIdReferer }

eveg_compare:
    path: /app/compare
    defaults: { _controller: evegAppBundle:Compare:compare }

# API Search
api_get_syntaxon_search:
    path: /api/syntaxons/search.{format}
    defaults: { _controller: evegAppBundle:SyntaxonSearch:simpleSearch, format: json }
    requirements:
        format:  json|xml
        _method: GET

# Admin routes
eveg_admin :
  resource: "routing_admin.yml"
  prefix:  /adminOld

eveg_app_admin_syntaxon:
    resource: "@evegAppBundle/Resources/config/routing/syntaxoncore.yml"
    prefix:   /admin/syntaxon