# src/eveg/AppBundle/Resources/config/routing/routing.yml

# application routes

eveg_app:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: eveg_app_homepage

eveg_app_homepage:
    locales:  { fr: "/accueil", en: "/en/homepage" }
    defaults: { _controller: evegAppBundle:Default:index }

eveg_app_howto:
    locales:  { fr: "/utiliser", en: "/en/howto" }
    defaults: { _controller: evegAppBundle:Default:howto }

eveg_app_contact:
    locales:  { fr: "/contact", en: "/en/contact" }
    defaults: { _controller: evegAppBundle:Default:contact }

# We use this trick because BeSimpleI18nRoutingBundle seems to be incompatible with FOSJsRoutingBundle (I think it doesn't recognize the "locales" parameter)
eveg_show_one_redirect:
    path: /app/redirect/{id}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: eveg_show_one

eveg_show_one:
    locales:  { fr: "/app/{id}", en: "/en/app/{id}" }
    defaults: { _controller: evegAppBundle:Default:showOne }
    requirements:
        id: \d+

eveg_show_photos:
    locales:  { fr: "/app/{id}/photos", en: "/en/app/{id}/photos" }
    defaults: { _controller: evegAppBundle:Default:showPhotos }
    requirements:
        id: \d+

eveg_edit_photo:
    locales: { fr:"/app/{id}/photo/{idPhoto}/modifier", en:"/en/app/{id}/photo/{idPhoto}/edit" }
    defaults: { _controller:evegAppBundle:SyntaxonPhoto:edit }
    requirements:
        id: \d+
        idPhoto: \d+

eveg_language:
    path: /language/{lang}
    defaults: { _controller: evegAppBundle:Default:setLanguage }
    requirements:
        lang: fr|en

eveg_repartition_filter:
    path: /app/repartition-filter
    defaults: { _controller : evegAppBundle:RepartitionFilter:repartitionFilter }
    requirements:
        _method: POST

eveg_add_photo:
    locales:  { fr: "/app/{id}/ajouter-une-photo", en: "/en/app/{id}/add-a-picture" }
    defaults: { _controller: evegAppBundle:SyntaxonPhoto:addPhoto }
    #requirements:
        #_method: POST GET

# API Search
api_get_syntaxon_search:
    path: /api/syntaxons/search.{format}
    defaults: { _controller: evegAppBundle:SyntaxonSearch:simpleSearch, format: json }
    requirements:
        format:  json|xml
        _method: GET

# Admin routes
eveg_admin :
  resource: "routing_admin.yml"
  prefix:  /adminOld

eveg_app_admin_syntaxon:
    resource: "@evegAppBundle/Resources/config/routing/syntaxoncore.yml"
    prefix:   /admin/syntaxon